name: Websites Publisher
on: [push]
jobs:
  website_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com/yazilim-vip"
      - name: npm Build
        run: |
          npm install
          npm build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  website_publish:
    needs: [website_build]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Prepare Deployment
        run: |
          echo "maemresen.com" > ./build/CNAME
      - name: GH Pages Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
